### ISSUE TITLE
System.AggregateException Exception when authenticating xbox users.

### ISSUE THREAD

**Issue by ayubhassan** [Microsoft/xbox-live-unity-plugin#110]
I keep getting this error when i try to sign in to xbox;

**System.AggregateException**: 'AggregateException_ctor_DefaultMessage'

**DETAILS**

  **InnerException**	 {System.NullReferenceException: Arg_NullReferenceException
   at Microsoft.Xbox.Services.System.TokenRequestResult..ctor(WebTokenRequestResult result)
   at Microsoft.Xbox.Services.System.AccountProvider.<GetTokenSilentlyAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 187
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 128
   at Microsoft.Xbox.Services.System.UserImpl.<InternalGetTokenAndSignatureHelperAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 187
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 128
   at Microsoft.Xbox.Services.System.UserImpl.<SignInImpl>d__51.MoveNext()}	System.Exception {System.NullReferenceException}

**Comment by ayubhassan** [comment]
Is anyone gonna give me an answer?

**Comment by jasonsandlin** [comment]
Don't know.  We haven't seen that one before.  Does it work when signing into PC, and only fail on the Xbox console?  

Email me your xboxservices.config and Package.appxmanifest at jasonsa@microsoft.com and we'll see if we can reproduce it.

**Comment by jasonsandlin** [comment]
Not sure if my email replies are getting to you.  

At https://developer.microsoft.com/en-us/xboxtestaccounts/configurecreators, can you add jasonsa@hotmail.com so I can sign-in into your sandbox.

**Comment by ayubhassan** [comment]
I added you

**Comment by jasonsandlin** [comment]
Hmm, I can't reproduce the issue on the Xbox Console.  I was able to sign into my test account using your app id and sandbox.  Here's the steps I did.  Can you confirm:

1) Change Xbox console sandbox to your sandbox (NRKVQH.0) and reboot the console
2) Sign-in with an account that has access to this sandbox (from https://developer.microsoft.com/en-us/xboxtestaccounts/configurecreators) 
3) Launch the game/sample app

**Comment by ayubhassan** [comment]
the problem has gone once i published my game to the store!

**Comment by jasonsandlin** [comment]
Good to hear
