### ISSUE TITLE
CreateSocialUserGroupFromList works on PC but fails on Xbox

### ISSUE THREAD

**Issue by mikeoliphant** [Microsoft/xbox-live-unity-plugin#120]
The "SignInAndProfile" example is failing to work for me, but only on the Xbox. It successfully signs in the user, but throws an error when trying to create the social user group - required to get the URL for the user's gamer pic. The same code works fine on PC.

Here is the error that is thrown:

`ArgumentException: You must add a local user before you can create a social group for them.
Parameter name: user
   at Microsoft.Xbox.Services.Social.Manager.SocialManager.CreateSocialUserGroupFromList(XboxLiveUser user, List`1 userIds)
   at UserProfile.<LoadProfileInfo>d__19.MoveNext()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)
   at UnityEngine.SetupCoroutine.$Invoke1InvokeMoveNext(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
`

**Comment by Piecrustius** [comment]
I have the opposite problem.  Mine works on the Xbox, but not on the PC.  My error on the PC is not quite the same:

Exception thrown: 'Microsoft.Xbox.Services.XboxException' in Microsoft.Xbox.Services.UWP.CSharp.dll
Exception thrown: 'Microsoft.Xbox.Services.XboxException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.AggregateException' in Assembly-CSharp.dll
'Test Social.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'D:\Develop\Test Social\build\Test Social\bin\x64\Debug\AppX\System.Diagnostics.StackTrace.dll'. Cannot find or open the PDB file.
AggregateException: One or more errors occurred. (Provider error: , Error Code: D000000D)
   at TaskYieldInstruction.get_keepWaiting()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)
   at UnityEngine.SetupCoroutine.$Invoke1InvokeMoveNext(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 

Maybe I have something configured incorrectly.

What is odd for me on the Xbox is that if I start debugging on the "Remote Machine", I will be signed in with the signed in user.  However, the gamer picture will be the default from the plugin, i.e., the "Fake User" image.  If I set a breakpoint at the "CreateSocialUserGroupFromList" line in UserProfile.cs and step slowly through a few lines until the yield statement and continue from there, the gamer picture is correct.

**Comment by mikeoliphant** [comment]
Piecrustius - I can't help with the exception you are getting, but I think there is a problem in UserProfile.cs that causes the issue with the gamer picture. It isn't waiting for the WWW call to finish downloading the image. I added:

`        while (!www.isDone)
        {
            yield return null;
        }
`

right after the WWW call in LoadProfileInfo() and that fixed the issue for me.

**Comment by Piecrustius** [comment]
Thanks, Mike. That did it for me.  I appreciate it.

**Comment by mikeoliphant** [comment]
Piecrustius - glad to help.

An update on my original issue - it turns out that it does not always fail on Xbox. It sometimes works and sometimes does not, with no code changes.

I would also like to add a related question - is this the only way to load a gamer picture? I don't have any other reason to create a social user group, but it is only way I can see to get access to the gamer picture.

**Comment by jasonsandlin** [comment]
Thanks Mike, we'll get that fix in.  We'll get back to you on the other questions

**Comment by MSFT-Heba** [comment]
@mikeoliphant: Regarding your other question, currently you need the social user group to access the gamer picture, yes. We'll look into this. Thanks.

**Comment by mikeoliphant** [comment]
I also seem to be seeing this problem a lot more consistently recently.

**Comment by mikeoliphant** [comment]
This issue seems to now be happening with my games that are in the Store on Xbox One. My games are no longer showing the user's gamer pic because this error keeps my code from getting access to it.

**Comment by johnrlisenby** [comment]
I am now getting the same issue. The fake user profile works, but when I build out the game for testing, I am getting the above issue.

**Comment by furiousflyer** [comment]
If I understand this thread. Gamer pic not pulling is known bug ? Any word on timeframe of the fix.
I am having an issue with gamer pic not pulling in a published game. If it is not a bug then I need to dig deeper in my code. My apologies if I am not reading the threads correctly.

**Comment by MSFT-Heba** [comment]
@furiousflyer With the new release v1804 we hope to have the pics loading more reliably. Would you mind giving it a try and letting us know how it worked for you?

**Comment by furiousflyer** [comment]
I have been away for a while. I am working on another update. I will try the new version and let you know how it turns out.
